language: r
sudo: false
cache: packages

env:
  _R_CHECK_FORCE_SUGGESTS_=false
  R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_cache: Rscript -e 'remotes::install_cran(c("pkgdown"))'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true
      on:
        repo: r-lib/devtools
        condition: $TRAVIS_BRANCH = master || -n $TRAVIS_TAG
  - r: oldrel
  - r: 3.3
  - r: 3.2

# We need to install BiocInstaller for testing Bioconductor packages
bioc_required: true

install:
  - git clone --depth 1 https://github.com/r-lib/remotes && R CMD build --no-build-vignettes remotes && R CMD INSTALL remotes*tar.gz && rm -rf remotes remotes*tar.gz
  - R -e 'install.packages("curl")' -e 'remotes::install_deps(".", dependencies = TRUE)'

# Only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
