# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh r_binary_install curl BiocManager

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

before_test:
  - cinst pandoc
  - ps: $env:Path += ";C:\Program Files (x86)\Pandoc\"

environment:
  global:
<<<<<<< HEAD
    WARNINGS_ARE_ERRORS: 1
=======
    WARNINGS_ARE_ERRORS: true
>>>>>>> upstream/master
    _R_CHECK_FORCE_SUGGESTS_: false
    R_ARCH: x64
    USE_RTOOLS: true ## to be able to use Remotes (i.e. packages from non-CRAN sources)

  matrix:
    - R_VERSION: release

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

cache:
  - C:\RLibrary
